### ISSUE TITLE
[Info] Debug rom differences

### ISSUE THREAD

**Issue by marijnvdwerf** [pret/pokeruby#138]
First column is the English 1.1, second is German 1.0, third is German debug.

http://marijnvdwerf.nl/u/1482242250-pokeruby-debug/

**Comment by YamaArashi** [comment]
Very nice. It looks like it wouldn't be too hard to add the debug ROM stuff under a debug ifdef.

**Comment by camthesaxman** [comment]
Thanks for your work on disassembling the debug ROM. I've finally gotten around to adding this in #541, so it looks like this issue can be closed now.
