### ISSUE TITLE
unknown_E81098 weirdness

### ISSUE THREAD

**Issue by marijnvdwerf** [pret/pokeruby#154]
![image](https://cloud.githubusercontent.com/assets/737603/21621586/f96b7c9c-d1f9-11e6-9b29-a394492a1137.png)
![image](https://cloud.githubusercontent.com/assets/737603/21621659/4b08002a-d1fa-11e6-8859-88db3a36ff2c.png)

`unknown_E81098` appears to be an 8bpp image. The palette appears to start at `gUnknown_083F86BC`, but seems to be longer than currently defined in the data file. `LoadPalette(gUnknown_083F86BC, 0, 448)` is called, but I'm having trouble to figure out where that means the data should end.

**Comment by YamaArashi** [comment]
Sometimes a group of palettes is loaded at once. It just loads the bytes from that address.

**Comment by marijnvdwerf** [comment]
The actual image also requires more palette data. So I'm unsure whether it's actually a separate palette.

**Comment by YamaArashi** [comment]
well, nothing seems to reference gRouletteCenter_Pal, so it is probably just a big palette

**Comment by camthesaxman** [comment]
Is this the same issue with gUnknown_081E764C in main_menu.c? In data2.s, there are two palettes incbinned there (`graphics/birch_speech/bg0.gbapal` and `graphics/birch_speech/bg1.gbapal`), and both get loaded at once. Should these be combined into one large palette?

**Comment by camthesaxman** [comment]
This was fixed over a year ago in 44dfc173df70162ef4e0a972cb1eab76ab5381a5
