### ISSUE TITLE
Claimed files

### ISSUE THREAD

**Issue by yenatch** [pret/pokeruby#186]
If you are decompiling a file, claim it here.

**Comment by ProjectRevoTPP** [comment]
I claim bike.s and braille_puzzle.s.

**Comment by yenatch** [comment]
- [ ] `rom_8077ABC.s`

**Comment by camthesaxman** [comment]
Currently working on battle_anim.c

**Comment by ProjectRevoTPP** [comment]
Unclaiming bike.s and letting someone else get that now.

**Comment by marijnvdwerf** [comment]
Wouldn't it be easier to use a GitHub project for this? So you can move claimed files across columns.

**Comment by ProjectRevoTPP** [comment]
Laziness I assume.

**Comment by ProjectRevoTPP** [comment]
- [ ] bike.s

**Comment by ProjectRevoTPP** [comment]
Ive created a GitHub project to replace this issue. I will leave this issue if anyone outside the listed decompilers wants to claim a file in the meantime.

**Comment by camthesaxman** [comment]
Nice. I'll get back to decompiling once I'm out of school for the summer. Someone else can claim field_map_obj. I kind of hit a roadblock with that file due to how the data was organized.

**Comment by DizzyEggg** [comment]
Claiming battle_4.s

**Comment by DizzyEggg** [comment]
Claiming battle_3.s

**Comment by DizzyEggg** [comment]
Claiming battle_message.s

**Comment by DizzyEggg** [comment]
Claiming egg_hatch

**Comment by DizzyEggg** [comment]
Claiming hall_of_fame

**Comment by ProjectRevoTPP** [comment]
I don't know why I didn't close this. We have a project for this now.
