### ISSUE TITLE
Decompile Engine Components

### ISSUE THREAD

**Issue by ProjectRevoTPP** [pret/pokeruby#260]
**Undecompiled**
- [x] m4a_3.s

**Decompiled/Available in C**
- [X] agb_flash.c
- [X] agb_flash_1m.c
- [X] agb_flash_le.c
- [X] agb_flash_mx.c
- [X] blend_palette.c
- [X] cable_club.c
- [X] clear_save_data_menu.c
- [X] clock.c
- [X] decompress.c
- [X] libc.c
- [X] link.c
- [X] load_save.c
- [X] m4a_2.c
- [X] m4a_4.c
- [X] m4a_tables.c
- [X] main.c
- [X] main_menu.c
- [X] menu.c
- [X] menu_cursor.c
- [X] mystery_event_menu.c
- [X] mystery_event_script.c
- [X] name_string_util.c
- [X] naming_screen.c
- [X] option_menu.c
- [X] palette.c
- [X] play_time.c
- [X] rtc.c
- [X] record_mixing.c
- [X] rng.c
- [X] save.c
- [X] save_failed_screen.c
- [X] save_menu_util.c
- [X] script.c
- [X] siirtc.c
- [X] sound.c
- [X] sound_check_menu.c
- [X] sprite.c
- [X] strings.c // actually a data file of nothing but engine-relevent strings
- [X] string_util.c
- [X] task.c
- [X] text.c
- [X] text_window.c
- [X] tileset_anim.c
- [X] time_events.c
- [X] trade.c
- [X] trainer_card.c
- [X] trig.c
- [X] util.c
- [X] reset_rtc_screen.c

**Comment by PikalaxALT** [comment]
Marking this complete
