### ISSUE TITLE
Decompile Field Menu & Scene Components

### ISSUE THREAD

**Issue by ProjectRevoTPP** [pret/pokeruby#263]
**Undecompiled**
 - [x] pokenav.s

**Decompiled**
 - [x] berry_tag_screen.c
 - [X] birch_pc.c
 - [X] choose_party.c
 - [x] coins.c
 - [x] coord_event_weather.c
 - [X] decoration_inventory.c
 - [x] dewford_trend.c
 - [x] diploma.c
 - [X] easy_chat.c
 - [x] event_data.c
 - [x] field_region_map.c
 - [x] field_message_box.c
 - [X] field_specials.c
 - [X] field_tasks.c
 - [x] hof_pc.c
 - [x] item.c
 - [x] item_use.c
 - [x] landmark.c
 - [x] lottery_corner.c
 - [x] map_name_popup.c
 - [x] money.c
 - [x] party_menu.c
 - [X] pokeblock.c
 - [X] pokeblock_feed.c
 - [x] player_pc.c
 - [X] roulette.c
 - [X] roulette_util.c
 - [x] script_menu.c
 - [x] shop.c
 - [X] slot_machine.c
 - [x] start_menu.c
 - [x] starter_choose.c
 - [X] use_pokeblock.c
 - [x] wallclock.c
 - [x] tv.c
 - [X] item_menu.c
 - [X] region_map.c
 - [x] trader.s
 - [x] fldeff_flash.s
 - [x] menu_helpers.s

**Comment by marijnvdwerf** [comment]
**Unfinished**
 - [ ] player_pc.s
 - [ ] party_menu.s
 - [ ] tv.s
 - [ ] shop.s

**Undecompiled**
 - [ ] birch_pc.s
 - [ ] choose_party.s
 - [ ] easy_chat.s
 - [ ] field_specials.s
 - [ ] field_tasks.s
 - [ ] pokenav.s
 - [ ] pokeblock.s
 - [ ] pokeblock_feed.s
 - [ ] roulette.s
 - [ ] roulette_util.s
 - [ ] slot_machine.s
 - [ ] use_pokeblock.s
 - [ ] menu_helpers.s
 - [ ] trader.s
 - [ ] fldeff_flash.s
 - [ ] decoration_inventory.s
 - [ ] item_menu.s
 - [ ] region_map.s

**Decompiled**
 - [x] berry_tag_screen.c
 - [x] coins.c
 - [x] coord_event_weather.c
 - [x] dewford_trend.c
 - [x] diploma.c
 - [x] event_data.c
 - [x] field_region_map.c
 - [x] field_message_box.c
 - [x] hof_pc.c
 - [x] item.c
 - [x] item_use.c
 - [x] landmark.c
 - [x] lottery_corner.c
 - [x] map_name_popup.c
 - [x] money.c
 - [x] party_menu.c
 - [x] player_pc.c
 - [x] script_menu.c
 - [x] shop.c
 - [x] start_menu.c
 - [x] starter_choose.c
 - [x] wallclock.c
 - [x] tv.c

**Comment by PikalaxALT** [comment]
Marking this complete
