### ISSUE TITLE
Decompile Battle System Components

### ISSUE THREAD

**Issue by ProjectRevoTPP** [pret/pokeruby#265]
**This system has been decompiled!**

**Decompiled**
- [X] battle_1.c
- [X] battle_2.c
- [X] battle_3.c
- [X] battle_4.c
- [X] battle_5.c
- [X] battle_6.c
- [X] battle_7.c
- [X] battle_8.c
- [X] battle_9.c
- [X] battle_10.c
- [X] battle_811DA74.c
- [X] battle_interface.c
- [X] battle_message.c
- [X] battle_party_menu.c
- [X] battle_records.c
- [X] battle_tower.c
- [X] battle_transition.c
- [X] battle_setup.c
- [X] battle_ai.c
- [X] calculate_base_damage.c // note: doesnt match but is probably functionally equivalent.
- [X] post_battle_event_funcs.c

**Comment by PikalaxALT** [comment]
Marking this complete
