### ISSUE TITLE
Decompile Battle Anim Components

### ISSUE THREAD

**Issue by ProjectRevoTPP** [pret/pokeruby#266]
**Undecompiled**
- [x] battle_anim_812C144.s
- [x] battle_anim_813F0F4.s

**Decompiled**
- [X] battle_anim_807B69C.c
- [X] battle_anim_80CA710.c
- [X] battle_anim_81258BC.c
- [X] pokeball.c
- [X] battle_anim.c
- [X] battle_anim_80A7E7C.c
- [X] smokescreen.c
- [X] battle_anim_8137220.c

**Comment by ProjectRevoTPP** [comment]
This section is very much outdated. Will update later. I will check 80C when all of its split files are decompiled.

**Comment by PikalaxALT** [comment]
Marking this complete
