### ISSUE TITLE
Decompile Pokemon Components

### ISSUE THREAD

**Issue by ProjectRevoTPP** [pret/pokeruby#267]
**Undecompiled**
- [x] pokemon_storage_system.s

**Decompiled**
- [X] pokedex.c
- [X] pokedex_area_screen.c
- [X] pokedex_cry_screen.c
- [X] pokemon_item_effect.c
- [X] pokemon_1.c
- [X] pokemon_2.c
- [X] pokemon_3.c
- [X] pokemon_menu.c
- [X] pokemon_size_record.c
- [X] pokemon_summary_screen.c
- [X] learn_move.c
- [X] mail.c
- [X] mail_data.c
- [X] mon_markings.c
- [X] pokemon_icon.c

**Comment by PikalaxALT** [comment]
Marking this complete
