### ISSUE TITLE
Pokeruby tools not existing

### ISSUE THREAD

**Issue by NewDenverCity** [pret/pokeruby#294]
The pokeruby tools for windows, at yamaarashi's github page, have been 404'd.

**Comment by camthesaxman** [comment]
Yes, we're aware of this. Yesterday, YamaArashi suddenly completely disappeared from the internet without giving any warning, and deleted his GitHub account. Here's the last version of the tools before they were deleted.
[pokeruby-tools-master.zip](https://github.com/pret/pokeruby/files/997082/pokeruby-tools-master.zip)

From now on, the tools will be hosted on ProjectRevoTPP's page. https://github.com/ProjectRevoTPP/pokeruby-tools

**Comment by yenatch** [comment]
The tools are now hosted at https://github.com/pret/pokeruby-tools.
