### ISSUE TITLE
GetNationalPokedexFlag name

### ISSUE THREAD

**Issue by DizzyEggg** [pret/pokeruby#395]
I think this function has a wrong name. It should be renamed to 'GetSetNationalPokedexFlag' or something similar, because it doesn't just get a flag, it can also set it.
Depending on the argument:
0 = get if seen
1 = get if caught
2 = set seen
3 = set caught

**Comment by PikalaxALT** [comment]
Has this issue been resolved?

**Comment by ketsuban** [comment]
Yes, it became `GetSetPokedexFlag` in #415.
