### ISSUE TITLE
SetMonData taking only const u8*

### ISSUE THREAD

**Issue by DizzyEggg** [pret/pokeruby#396]
The 'SetMonData' function takes the third argument as const u8* which I think should be changed to const void*, because of ugly casting that happens whenever that function is called and the set data is a hword or a word.

**Comment by camthesaxman** [comment]
I hate the casting too, but from looking at how `SetMonData` treats that parameter internally, it seems that it should actually be a `u8 *`. It does the whole "combine larger integer from bytes" thing instead of casting to the appropriate pointer.

**Comment by ProjectRevoTPP** [comment]
Fixed in #450 .
