### ISSUE TITLE
I'd like to help

### ISSUE THREAD

**Issue by DizzyEggg** [pret/pokeruby#40]
See above. I've got some documented stuff on Emerald. Wouldn't mind starting pokeEmerald if I knew how it all is done. Tried contacting you, didn't work. My profile on PokeCommunity http://www.pokecommunity.com/member.php?u=454295.

**Comment by ProjectRevoTPP** [comment]
https://github.com/pret/pokeemerald

**Comment by camthesaxman** [comment]
Well, you can open a pull request for pokeemerald if there's something you want to add. If you have questions or need any help on reverse engineering, go to our IRC channel #pret on irc.freenode.net.
