### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by BlackWhiteRobin** [pret/pokeruby#405]
I only recently joined the hype train on this and I've been trying to compile it to no avail. Here's what I did:

Copied pokeruby-tools/tools inside pokeruby-master/tools
Opened MSYS from the start menu.
Changed directory to the root of the project.
Typed make.
Error: "make: *** [build/ruby/sym_bss.ld] Error 123"
Typed make ruby.
Error: "make: *** [build/ruby/agb_flash.o] Error 127"

Sorry if this is a very noobish issue. Your instructions were very vague too. I suggest rewriting it. Thank you for the time. :)

**Comment by ProjectRevoTPP** [comment]
Do you have devkitpro installed and linked within your environment properly?

**Comment by BlackWhiteRobin** [comment]
Yes I have. I've been using it since DizzyEgg's things for EM. :)

**Comment by yenatch** [comment]
make's errors aren't much use. Can you post the full output (or at least the errors leading up to the final one)?

**Comment by ProjectRevoTPP** [comment]
Do you have an up to date devkitpro? We made some changes a little while ago which unfortunately broke older devkitpros being able to build pokeruby.

**Comment by camthesaxman** [comment]
devkitARM r46 or r47 are required. Older versions don't build a matching ROM due to an alignment bug in the linker.

**Comment by BlackWhiteRobin** [comment]
Alright. I just updated my devkitARM to r47 but I'm still getting the same error. Something about preproc.exe not being able to start.

**Comment by ProjectRevoTPP** [comment]
what path is preproc.exe? It should be pokeruby/tools/preproc/preproc.exe, where pokeruby is your working directory.

**Comment by yenatch** [comment]
The install instructions mention that there are some tools needed to build. On Windows, if you don't want to build them, you can download them:
>Then get the compiled tools from https://github.com/pret/pokeruby-tools. Copy the tools/ folder over the tools/ folder in your pokeruby directory.

**Comment by BlackWhiteRobin** [comment]
It's there. It's in the correct directory.

I noticed though that it seems to be finding files with ".o" extension. I checked the directory where it is trying to find the said files and I found the exact same files just with the extension ".i" and ".s"

**Comment by BlackWhiteRobin** [comment]
I obviously already read that and got them.

**Comment by yenatch** [comment]
What is the exact error?

**Comment by BlackWhiteRobin** [comment]
Okay, I'll run over this again.

1. I run "make" in the root directory which is "pokeruby-master"
2. Error prompt by "preproc.exe" not being able to start correctly thus "0xc000007b"
3. I noticed that it is trying to find files with ".o" extension in the "build/ruby/src/" folder and when I went there, there are files with the exact same name but with ".i" and ".s" extension. (e.g. agb_flash.o is missing but there is agb_flash.i and agb_flash.s)

**Comment by ProjectRevoTPP** [comment]
You need to copy paste the full error.

**Comment by BlackWhiteRobin** [comment]
Shall I post an image? Wait.

**Comment by BlackWhiteRobin** [comment]
This is the error when I type in "make"
https://i.imgur.com/UW7RFBi.png
This one after I press "OK"
https://i.imgur.com/gs2XpAf.png

**Comment by yenatch** [comment]
You need to use the msys terminal. It should be under programs. If not, you can run `C:\\devkitPro\msys\msys.bat`.

Will fix the instructions to mention this.

**Comment by BlackWhiteRobin** [comment]
I actually did this beforehand. Still the same results.

**Comment by ProjectRevoTPP** [comment]
Your window says cmd.exe. You're running CMD and not MSYS.

**Comment by BlackWhiteRobin** [comment]
No no. I actually did use MSYS before. I just used cmd for the sake of that screenshot. I was in a hurry. Still don't believe me? I used MSYS again just now it just says the same exact things as those in the screenshot.

**Comment by yenatch** [comment]
Ok, I think I know what it is. Some of the tools also need Visual C++ to work. This is mentioned on the pokeruby-tools page but not in the instructions.
>You may need the Visual C++ runtime DLL to run some of these executables. Please choose the file called `vc_redist.x86.exe`.

You can get it here. https://www.microsoft.com/en-us/download/details.aspx?id=5555

**Comment by BlackWhiteRobin** [comment]
Alright. Just came back installing everything. Actually, I even installed every version of Visual C++. Still doesn't work. I think pokeruby just hates me. If it's bothering you too much now, don't mind me anymore. I mean it works on everyone else except me. Majority works, and I'm the only one who can't make it work so it must be my problem. So yeah. Thanks for the efforts though. Maybe I won't get to touch this ever. :)

**Comment by yenatch** [comment]
Maybe I gave you the wrong link. Try a newer one from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads.

**Comment by BlackWhiteRobin** [comment]
Like I said, I installed every version of Visual C++ to make sure all whatever DLLs are there. Still to no avail. I'm sorry for the inconvenience.

**Comment by yenatch** [comment]
Were they 32-bit or 64? The tools need 32.

**Comment by camthesaxman** [comment]
Visual C++ 2015 32-bit is the specific one you need.
I believe 0xc000007b means that some file needed to run the program is corrupt or misconfigured.

**Comment by BlackWhiteRobin** [comment]
Yep. It works now. Sorry for the late notice. Thanks everyone for not giving up on me. :D
