### ISSUE TITLE
Preproc-filtered assembly causes faulty line numbers in AS errors

### ISSUE THREAD

**Issue by marijnvdwerf** [pret/pokeruby#409]
If `preproc` comes across a global label, it inserts a new line with the global command.

```
test.s

1 _stuff:
2    . string "foo"
3
4 _bar:
5     .string "bar"
6
7 kStuff::
8     .4byte _stuff
9     .4byte_bar
```

```
test.s.i

 1 # 1 test.s
 2 _stuff:
 3    . string "foo"
 4
 5 _bar:
 6     .string "bar"
 7
 8     .global kStuff
 9 kStuff:
10     .4byte _stuff
11     .4byte_bar
```

Starting from line 7, everything shifts downward. When you get a compiler error, it refers to line 10, which doesn't even exist in the original.

```
test.s.i

 1 # 1 test.s
 2 _stuff:
 3    . string "foo"
 4
 5 _bar:
 6     .string "bar"
 7
 8     .global kStuff
 9 # 7 test.s
10 kStuff:
11     .4byte _stuff
12     .4byte_bar
```

Adding a location comment after the `.global` line, would probably correct these issues.

**Comment by camthesaxman** [comment]
I've also noticed wrong line numbers C files, like sprite.c.
