### ISSUE TITLE
Map Editor integration.

### ISSUE THREAD

**Issue by ProjectRevoTPP** [pret/pokeruby#428]
Currently, one of the problems with not having an approachable dissassembly is that no gen 3 map editors support integration with pokeruby. This will also apply to other gen 3 dissassemblies in the future. How do we wanna do this? Refactor maps/ ? Add JSON files to tell the editor where to look?

**Comment by waffln** [comment]
Porymap seems to work with the english version of pokeruby. Maybe this issue can be closed.
Right now i can't get Porymap to work with the german files.

**Comment by GriffinRichards** [comment]
> Right now i can't get Porymap to work with the german files.

5d55531
