### ISSUE TITLE
I have an problem with the Background Music

### ISSUE THREAD

**Issue by satoshifurude** [pret/pokeruby#438]
The issur is while pokemon cry Comes up in battle or what ever freezes an Instrument of the BackgroundMusic. Or this already fixed for win 10 Compiler users? Sorry for my bad english.

**Comment by Lun0s** [comment]
Did you by any chance compiled using devkitARM r45? If so, that's your problem.
Use r46 or r47 and everything should be fine.

**Comment by camthesaxman** [comment]
Please run `make compare`. If it says `pokeruby.gba: OK` at the end, then the ROM has built correctly and the problem is with whatever emulator you are using.

**Comment by satoshifurude** [comment]
@Lun0s thanks is was the devkitarm i used r45 i updated to r47 now is fixed then can this issur be closed.
