### ISSUE TITLE
Disambiguate macro names for Speed and Sp. Def stats

### ISSUE THREAD

**Issue by sphericalice** [pret/pokeruby#441]
Currently, MON_DATA_SPD is an ambiguous macro name as outside of the context of MON_DATA_SPDEF it is unclear if it refers to the Speed stat or the Special Defense stat.

Either settle on a consistent length and use SPE for Speed:

- MON_DATA_SPA
- MON_DATA_SPD
- MON_DATA_SPE

Or spell out SPEED in full:

- MON_DATA_SPATK
- MON_DATA_SPDEF
- MON_DATA_SPEED
Note that SPEED is five characters, which is the same as SPATK and SPDEF which is currently in use.

The former is arguably easier, but the latter is completely unambiguous while being slightly more verbose.

**Comment by camthesaxman** [comment]
Agreed. I found this confusing when decompiling some of the code.

**Comment by camthesaxman** [comment]
fixed in fd69fc936729c288720a7e5251314efa121e9ac3
