### ISSUE TITLE
Cant edit black and white images

### ISSUE THREAD

**Issue by igorfs10** [pret/pokeruby#442]
When I try to edit black and white images, it does not appear correctly in the game. The image looks like it is in a different type because it always increases the size when saved. Is there any way to get it to compile properly or software that can edit it?
I already tried with GIMP, Paint, Paint XP, GraphicsGale, Irfanview and Photoshop. All with palette file too.

![pokeruby_rev2-6](https://user-images.githubusercontent.com/25492239/31319539-8e641644-ac3b-11e7-8386-63e11a5b6e79.png)

**Comment by yenatch** [comment]
In Graphics Gale, you have to uncheck `Match Pixels with Colors` when loading the palette. I assume the other programs do this automatically without asking.

**Comment by igorfs10** [comment]
I've already tried. It didn't work.
Can you edit? Maybe there is a setting somewhere to save the image.
Is it possible to add something to convert the image to a "compatible type" at compile time?
I've been trying to fix this problem for some time and I dont know what to do now.

**Comment by ProjectRevoTPP** [comment]
What image is this?

**Comment by igorfs10** [comment]
This is the status_screen in interface folder. This happen with misc in contest folder too. I did not try but I think it happens with the other black and white images.

**Comment by camthesaxman** [comment]
These grayscale images should always be exported as grayscale with a color depth of 16. If the editor you use messes with the color depth or color type, then it's not going to look right in game. I'm currently working on this issue as we speak.

**Comment by igorfs10** [comment]
I tried to change to grayscale and 16 color depth in Graphicsgale and not worked. Thanks for your work on this issue.

**Comment by camthesaxman** [comment]
This seems to be a very strange image, indeed. There are actually 5 separate palettes that are used with these tiles, and they get selected based on what screen you are on, and different tiles can use different palettes. I have no idea how to make this more easily editable in a sane way. I've been able to convert most of the graphics to just use the palettes stored in the png file, rather than an external .pal file, but I don't know what to do about this one.

**Comment by yenatch** [comment]
You could use the tilemap to generate a png with the correct colors for each tile (and accept that format in gbagfx). The only problem then is enforcing tile colors in the editor. You would have to edit it very carefully. We'd probably get a lot of people who didn't realize you needed to do that. So maybe greyscale is better.

**Comment by igorfs10** [comment]
Do you know some way to save the image without causing problems in the game? I dont need to change the palette, I'm just going to change the text that is in image.

**Comment by camthesaxman** [comment]
Can you upload the edited png that's causing problems? I can examine it and see what the issue is.

**Comment by igorfs10** [comment]
https://raw.githubusercontent.com/Thebluehedgehog/pokeruby/8a1d74583ab517d5efa4b41d7175e6bf9ea8a266/graphics/contest/misc.png
this is the contest image

**Comment by igorfs10** [comment]
I found a way to edit. I had to change the palette using different colors and edit it with graphicsgale. If you use similar color the graphicsgale changes to the first color in the palette and this cause some issues with various black colors. Should I close this issue?
