### ISSUE TITLE
Is the disassembly makeable on the current state?

### ISSUE THREAD

**Issue by hbdfreitas** [pret/pokeruby#45]
I got several errors while trying to compile the makefile. I have my baserom.gba has the correct sha1 checksum.

**Comment by YamaArashi** [comment]
It builds for me and several others at least. What were the errors you got?

**Comment by hbdfreitas** [comment]
I got a near a gazillion undefined references errors after using the make command. I used the prebuilt binaries.

**Comment by YamaArashi** [comment]
If you do something like "make >out.txt", can you see any earlier errors before the undefined reference ones? Unfortunately, the makefile got a bit weird after support for building both Ruby and Emerald at the same time was added.

**Comment by YamaArashi** [comment]
Actually, to see the errors you would need to do "make 2>errors.txt".

**Comment by hbdfreitas** [comment]
[errors.txt](https://github.com/pret/pokeruby/files/488564/errors.txt)

**Comment by yenatch** [comment]
```
make clean
```

**Comment by hbdfreitas** [comment]
That actually worked apparently. Can't see any output file in my pokeruby folder though.

**Comment by yenatch** [comment]
That deleted all the files created by the build, in case they were created in failed attempts. What happens when you run `make` again?

**Comment by hbdfreitas** [comment]
Worked like a charm! Made both Ruby and Sapphire. Gotta try to make some edits to see if they actually take effect. Thanks for all the help!

**Comment by YamaArashi** [comment]
I've updated the makefile so that build issues will be less likely. Now it will only make either Ruby or Sapphire, but not both, depending on the target you pass to `make`.

**Comment by hbdfreitas** [comment]
I'll try the new makefile. Thanks for all the help. Wish you guys the best of luck. I understand that disassembling a game like this is massive work and though my knowledge is very limited, I'd be glad to of some help. Are there any tutorials out there that would help me understand the pocess better so I could be of some use for this project?

**Comment by YamaArashi** [comment]
You mean a tutorial on disassembling? I'm not sure if I have seen one. But you can ask questions on this IRC channel if you have any. Were you able to successfully make changes to the game?

irc: [freenode#pret][irc]

[irc]: https://kiwiirc.com/client/irc.freenode.net/?#pret

**Comment by hbdfreitas** [comment]
I was able to make a few text changes, and it compiled flawlessly. Might try to add new Pokémon later. 
How far is this project from being complete? Thanks for all the help.

**Comment by YamaArashi** [comment]
It depends on how you measure it. There isn't much data left to dump until the base ROM is no longer needed. But we still need to figure out what a lot of the data is for. There are many "gUnknown_08XXXXXX" labels which need to be given proper names. In addition, I am trying to decompile the assembly code into C, which will take quite a while.

**Comment by hbdfreitas** [comment]
I understand. Again, best of luck on your endeavor. Maybe I'll drop by on irc sometime. =)

Gonna close as of now.
