### ISSUE TITLE
Compilation yields incorrect checksum (wrong addresses in iwram)

### ISSUE THREAD

**Issue by LIJI32** [pret/pokeruby#523]
Compilation yields incorrect checksum for all targets. After comparing the original and built ROMs (I used pokeruby_rev2 for comparison), it seems that some variables in iwram were assigned incorrect addresses (the assigned addresses were 4 or 8 bytes higher). For example, `gUnknown_030005A0` is correctly assigned to `0x030005A0`, but `gUnknown_030005A4` is assigned to `0x030005A8` and `gLinkTransferringData` is assigned to to `0x300176C` instead of `0x3001764`.

**Comment by LIJI32** [comment]
It seems that for some reason, the size of the `.bss`section is being rounded to a multiple of 8 per .o file.

**Comment by ProjectRevoTPP** [comment]
Are you using devkitpro r46 or later?

**Comment by LIJI32** [comment]
Yes, r47. Should I downgrade to r45?

**Comment by LIJI32** [comment]
Duh, apparently I downloaded r47 but still used some old version I already had installed. Seems to work now. :)
