### ISSUE TITLE
Nohara debug menu: Pointers instead of string data

### ISSUE THREAD

**Issue by aplumafreak500** [pret/pokeruby#575]
https://github.com/pret/pokeruby/blob/cf0a2d453d514c76095f9d7eeb06f982d7e7357d/data/debug_menu_nohara.s#L100

https://github.com/pret/pokeruby/blob/cf0a2d453d514c76095f9d7eeb06f982d7e7357d/data/debug_menu_nohara.s#L109

These look like pointers, not string data. Maybe they're string tables for the TV debug menu?

**Comment by camthesaxman** [comment]
Yes, these were dumped incorrectly. Will fix.

**Comment by camthesaxman** [comment]
fixed in 214702b4e0a49c843099cb67a3fd2251d59a1566
