### ISSUE TITLE
It would be nice to add some tutorials into the Wiki

### ISSUE THREAD

**Issue by Shiny-andKittens** [pret/pokeruby#655]
Pokemon Crystal has all the tutorials it needs, but this one (and others) don’t, even though the range of possibilities is larger for RSE.

Is there a reason, or has it just not been done?

**Comment by Delta456** [comment]
Well, Pokecrystal has more tutorials because it has a lot of documentation and is completely disassembled I believe. I think you should wait for PokeRuby to be completed and wait for more documentation. I think someone will surely make it.

**Comment by Shiny-andKittens** [comment]
Thank you.
