### ISSUE TITLE
How do I disassemble Ruby?

### ISSUE THREAD

**Issue by Shiny-andKittens** [pret/pokeruby#656]
I’d honestly like to help, except I don’t know how.

Are there disassemblers I should use? How should I use them, how do I separate the code, etc.

Thanks.

**Comment by Shiny-andKittens** [comment]
Thank you once again

**Comment by Shiny-andKittens** [comment]
I have another question @Delta456, I see some .s files in other folders, even src/.

What are those specifically?

**Comment by ProjectRevoTPP** [comment]
.s files are assembly files. These are already dissassembled. The ones in src/ are because they're handwritten and not compiled code. asm/ is reserved for undecompiled code that needs to become C source code in the future.

**Comment by Shiny-andKittens** [comment]
Thank you very much, I’ll soon be reading the instructions very carefully and then end up needing help again. :P
