### ISSUE TITLE
libgcc.a missing

### ISSUE THREAD

**Issue by LordRyst** [pret/pokeruby#704]
Just trying to start up working with this project, and install fails on both linux and windows at the same place.

```
ricks@DESKTOP-CIOG5IH ~/agbcc/libgcc
$ make clean
Makefile:1: /cygdrive/c/devkitpro/devkitARM/base_tools: No such file or directory
make: *** No rule to make target '/cygdrive/c/devkitpro/devkitARM/base_tools'.  Stop.
```

**Comment by PikalaxALT** [comment]
Paths are case sensitive. Make sure your $DEVKITPRO variable points to the correct path for your devkitPro installation, and that your devkitPro is up to date.

**Comment by LordRyst** [comment]
Thank you. INSTALL.md lists windows install directory for devkitPro as "devkitpro", but the current default is "devkitPro". Wonderful point of confusion.

**Comment by LordRyst** [comment]
And another note, when installing devkitPro, package gc32 is needed.

**Comment by LordRyst** [comment]
And I'm up and working. Thanks, I still recommend some minor changes to the install.md, for the windows install.

**Comment by DeeDeeG** [comment]
I had this issue also. Might be worth a comment here that says "you might need to change this to lowercase `devkitpro`"?

https://github.com/pret/pokeruby/blob/master/INSTALL.md#linux
